### ISSUE TITLE
London Bridge event - late May

### ISSUE THREAD

**Issue by ultrasaurus** [bridgefoundry/organizing#7]
London has an incredible tech community with many active bridges.  Sarah Allen (@ultrasaurus) will be visiting UK before/after [KubeCon](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/) May 20-23.  We have interest in event sponsorship and it would be great to get the different groups together, and share what's been going on across the pond and in other parts of the world!

TODO
- [x] local organizers: Eggya Chiquita (WWG/GoBridge), Mirah Gary (Pivotal), @annabee (ScalaBridge)
- [x] venue - Pivotal Labs Monday
- [x] when exactly?  May 28 evening 6-9 PM
- [x] event description - draft below
- [x] sponsor prospectus - [DRAFT](https://docs.google.com/presentation/d/1h2antJbg6YWYLtdqSm-BmnC7GoNH1NW8yXWKAynwM5Q/edit#slide=id.g58d6f50819_0_0)
- [x] post the event and invite people

## Community Celebration

2-3 hour event celebrating diversity in technology. The event would bring together students, volunteers, teachers and organizers from across all UK bridges to celebrate their work and share ideas. As with all Bridge events, the idea would be to provide food and drink and create a space for sharing and community.

The event would include approximately 1 hour of structured storytelling with time before and after for informal networking.

> London Bridges Celebrate Tech Inclusion
> Buffet dinner and drinks provide networking time followed by presentation about the impact that Railsbridge, ClojureBridge, GoBridge and ScalaBridge are having in the UK and beyond.  
> Opening keynote by Sarah Allen, Bridge Foundry Executive Director.

Confirmed speakers
* Rosa Fox, RailsBridge (maybe Emma will join?)
* Eggya Chiquita, Women Who Go / GoBridge
* John Stevenson, ClojureBridge
* Anna Bladzich, ScalaBridge

## Industry & Bridge leader gathering

> UK Leadership Circle
> Small gathering of industry leaders & open source tech community leaders. We’ll discuss what makes successful software teams and how to move the industry forward.

**Comment by ultrasaurus** [comment]
Note: May 27 is a holiday in the UK

Tues, May 28 evening dinner?

**Comment by ultrasaurus** [comment]
FYI: Pivotal Labs can host in their London office

**Comment by annabee** [comment]
Hello! I'm co-running ScalaBridge London and happy to be one of the local organisers for the event.

**Comment by ultrasaurus** [comment]
hi @annabee -- thank you so much for volunteering!  Can you sign up at https://www.bridgetroll.org -- I just made a draft event for volunteers:

![image](https://user-images.githubusercontent.com/41906/57187507-c3ca0780-6ea4-11e9-80b9-3d5723da9dce.png)

Once someone reviews the text, I can post and add you as an organizer!

**Comment by ilen** [comment]
Reviewed, looks ok to me.

**Comment by ultrasaurus** [comment]
Call for volunteers posted: https://www.bridgetroll.org/events/477
* added @jr0cket and @Rosa-Fox as co-organizers since I could find their bridge troll users
* @annabee  - drop in a link to your bridge troll profile page and then we can add you as co-organizer

**Comment by ultrasaurus** [comment]
Updated comment at top with progress -- thanks everyone!

**Comment by eggya** [comment]
Hello all, hope I'm not too late, I'm London based and happy to help wherever I can.
My bridge troll profile lives here: https://www.bridgetroll.org/users/8868/profile

**Comment by ultrasaurus** [comment]
We had the event.  It was awesome. Opened separate issue for blog post: https://github.com/bridgefoundry/bridgefoundry.github.io/issues/129
